### ISSUE TITLE
strip comments

### ISSUE THREAD

**Issue by adon-at-work** [yahoo/html-purify#10]
should strip comment patterns such as  `--> abc` and `abc <!--`
- require handling of unbalanced comments
- remove by default, and how abt making it configurable

**Comment by yukinying** [comment]
Could you elaborate the rationale of stripping those in details? 
// cc @neraliu @maditya

**Comment by adon-at-work** [comment]
i think it's obvious that the attack vectors can eliminate trusted inputs, given `--> abc` and `abc <!--` are left untouched by html-purifier.

``` html
<script>
// untrusted inputs collected from malicious users
var subject = 'abc<!--', content = '--> abc';
</script>

<div> Blah blah blah...
<p class="subject"><script>document.write(purify(subject));</script></p>
....something important here ...
<p class="body" onclick="expand()"><script>document.write(purify(content));</script></p>
</div>
```

**Comment by adon-at-work** [comment]
made a PR https://github.com/yahoo/html-purify/issues/18

**Comment by yukinying** [comment]
I think it is not only comment block having the issue. It looks like html-purify should ensure the output is ending in DATA state.

**Comment by yukinying** [comment]
Or just trim the end of the input to the last DATA state seen.

**Comment by adon-at-work** [comment]
> It looks like html-purify should ensure the output is ending in DATA state.

To do this, we need to:
- echo output only when tag closed (literally when > is encountered), read the code, DONE.
- balance tags, so output won't open/close tags for trusted inputs, or end up in special data states (e.g., RCDATA introduced by an unclosed `<textarea>`).  DONE.
- strip/balance comments, DONE by this PR
- eliminate character references, HARD (as CP does not have states for that)

**Comment by maditya** [comment]
> I think it is not only comment block having the issue. It looks like html-purify should ensure the output is ending in DATA state.

Should we really deal with partial HTML? I'd expect the user to call purify only on the final/full formed html. If the output is going to be appended to other data in some way, can we guarantee that it remains safe?

**Comment by adon-at-work** [comment]
> Should we really deal with partial HTML? I'd expect the user to call purify only on the final/full formed html.

I think the reason to use purify is that the HTML input is untrusted.
So, we cannot make assumptions on whether the HTML is full/final, right?

> If the output is going to be appended to other data in some way, can we guarantee that it remains safe?

Example in Mail: appends an untrusted HTML email to a webmail interface.
I believe Mail expects such a guarantee.

**Comment by adon-at-work** [comment]
the PR is merged, will close this soon if no further comments

**Comment by yukinying** [comment]
@maditya : 

> Should we really deal with partial HTML? I'd expect the user to call purify only on the final/full formed html. If the output is going to be appended to other data in some way, can we guarantee that it remains safe

I think the requirement for html-purify would be emitting final and full formed HTML, thus the output MUST end in DATA state.

**Comment by yukinying** [comment]
Talked to @maditya , the actual fix is to patch https://github.com/yahoo/html-purify/blob/master/src/derived-states.js#L27

**Comment by maditya** [comment]
Re-opening it to address https://github.com/yahoo/html-purify/pull/18#discussion_r35743499
