### ISSUE TITLE
publish 1.1.0 to npm

### ISSUE THREAD

**Issue by johndaley-me** [yahoo/html-purify#27]
Can 1.1.0 please be made available via npm?

Only 1.0.1 is available currently.

Also, I noticed that package.json has version 1.0.1 for the commit tagged at v1.1.0.

Thank you for this excellent package.

**Comment by ramijarrar** [comment]
Also noticed this. Would be great if this was addressed soon.

**Comment by johndaley-me** [comment]
I am unable to install directly with `npm install html-purify` but can install directly from GitHub as a workaround.

There is also a related issue addressed by PR #28.

**Comment by maditya** [comment]
v1.1.0 is now published on npm registry
