### ISSUE TITLE
self closing handling code review

### ISSUE THREAD

**Issue by neraliu** [yahoo/html-purify#3]
i have reviewed the code and found that only the transition from state 34 "Before attribute name state" to 43 "Self-closing start tag state" will mark it as the self closing tag, is it intentionally that we only regard this as self closing tag? as there are few state transition to 43 when solidus is encountered.

and i found that there is no reset of the self closing flag in the code. based on the spec, when the solidus is encountered, it will jump into the "self-closing start tag state", however, it can transits back to state 34 if "Anything else" is encountered. coincidentally, the canonicalization help to address this issue as the solidus will be trimmed out.

```
<img src="xxx" / id="xxx">
```

will be converted to

```
<img src="xxx"   id="xxx">
```

**Comment by maditya** [comment]
https://github.com/yahoo/html-purify/issues/11 addresses this issue
